/**
 * The html and text content generated by the copy/cut action
 */
export interface TextAndHtmlContentForCopy {
    /**
     * The HTML Content modified by the beforeCutCopy event
     */
    htmlContent: HTMLDivElement;
    /**
     * The content model modified by the beforeCutCopy event in plain text
     */
    textContent: string;
}
