name: Build and Deploy
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # v2.3.1
              with:
                  persist-credentials: false

            - name: Set Node Version
              uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
              with:
                  node-version: 'v18.16.0'

            - name: Install dependencies
              run: yarn

            - name: Build
              run: npm run-script build:ci

            - name: Install Firefox
              uses: browser-actions/setup-firefox@latest

            - name: Generate code coverage report
              uses: GabrielBB/xvfb-action@86d97bde4a65fe9b290c0b3fb92c2c4ed0e5302d # v1.6
              with:
                  run: npm run-script test:coverage

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@e80c869f0057899fc2cd28819b5bbe9de890524a # 3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist/deploy
                  CLEAN_EXCLUDE: '["pr-preview/**"]'
