name: Publish smaller package
on:
    push:
        branches:
            - master
jobs:
    publish-smaller-pack:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Set Node Version
              uses: actions/setup-node@v2
              with:
                  node-version: 'v14.18.2'

            - name: Install dependencies
              run: npm install

            - name: Preprocess package and const enum
              run: node tools/build.js replaceConstEnum

            - name: Build
              run: npm run-script build:ci

            - name: Publish
              run: node tools/build.js publish --token ${{ secrets.NPM_TOKEN }}
