name: Run Test on Firefox
on: push
jobs:
    run-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install dependencies
              run: npm install

            - name: Install Firefox
              uses: browser-actions/setup-firefox@latest

            - name: Test with Firefox
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: npm run-script test
